/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/nuTyfgTDm3U
 */
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { useState } from "react";

interface LoginProps {
  onSubmit: (values: { email: string; password: string }) => void;
}

export function LoginForm({ onSubmit }: LoginProps) {
  const [form, setForm] = useState({
    email: "",
    password: "",
  });

  const handleForm = (value: string, key: string) => {
    setForm({
      ...form,
      [key]: value,
    });
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-2xl font-bold">Login</CardTitle>
        <CardDescription>
          Enter your email below to login to your account
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input
              id="email"
              placeholder="m@example.com"
              required
              type="email"
              value={form.email}
              onChange={(e) => handleForm(e.target.value, "email")}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="password">Password</Label>
            <Input
              id="password"
              required
              type="password"
              value={form.password}
              onChange={(e) => handleForm(e.target.value, "password")}
            />
          </div>
        </div>
      </CardContent>
      <CardFooter>
        <Button
          disabled={!form.email || !form.password}
          onClick={() => onSubmit(form)}
          className="w-full"
        >
          Login
        </Button>
      </CardFooter>
    </Card>
  );
}
