/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/O7PBuHvcr1S
 */
import { Button } from "@/components/ui/button";

interface ProductListProps {
  handleAddCart: (value: string) => void;
}

export function ProductList({ handleAddCart }: ProductListProps) {
  return (
    <section className="grid grid-cols-1 gap-6 md:grid-cols-2 md:gap-8 lg:grid-cols-3 xl:grid-cols-4 w-full px-10 h-fit">
      <div className="flex flex-col rounded-lg overflow-hidden">
        <div className="flex-shrink-0 relative aspect-w-4 aspect-h-3">
          <img
            alt="Product 1"
            className="object-cover w-full h-full"
            height={300}
            src="/placeholder.svg"
            style={{
              aspectRatio: "400/300",
              objectFit: "cover",
            }}
            width={400}
          />
        </div>
        <div className="flex-1 grid grid-rows-2 p-4 gap-2">
          <div className="space-y-1">
            <h3 className="font-semibold text-base md:text-sm lg:text-base xl:text-sm">
              Classic T-Shirt
            </h3>
            <p className="font-normal text-sm md:text-xs lg:text-sm xl:text-xs text-gray-500 dark:text-gray-400">
              Soft and comfortable
            </p>
          </div>
          <div className="flex items-center justify-between">
            <h4 className="font-semibold text-sm md:text-xs lg:text-sm xl:text-xs">
              $19.99
            </h4>
            <Button size="sm" onClick={() => handleAddCart("Classic T-Shirt")}>
              Add to Cart
            </Button>
          </div>
        </div>
      </div>
      <div className="flex flex-col rounded-lg overflow-hidden">
        <div className="flex-shrink-0 relative aspect-w-4 aspect-h-3">
          <img
            alt="Product 2"
            className="object-cover w-full h-full"
            height={300}
            src="/placeholder.svg"
            style={{
              aspectRatio: "400/300",
              objectFit: "cover",
            }}
            width={400}
          />
        </div>
        <div className="grid grid-rows-2 p-4 gap-2">
          <div className="space-y-1">
            <h3 className="font-semibold text-base md:text-sm lg:text-base xl:text-sm">
              Denim Jeans
            </h3>
            <p className="font-normal text-sm md:text-xs lg:text-sm xl:text-xs text-gray-500 dark:text-gray-400">
              Stylish and durable
            </p>
          </div>
          <div className="flex items-center justify-between">
            <h4 className="font-semibold text-sm md:text-xs lg:text-sm xl:text-xs">
              $39.99
            </h4>
            <Button size="sm" onClick={() => handleAddCart("Denim Jeans")}>
              Add to Cart
            </Button>
          </div>
        </div>
      </div>
      <div className="flex flex-col rounded-lg overflow-hidden">
        <div className="flex-shrink-0 relative aspect-w-4 aspect-h-3">
          <img
            alt="Product 3"
            className="object-cover w-full h-full"
            height={300}
            src="/placeholder.svg"
            style={{
              aspectRatio: "400/300",
              objectFit: "cover",
            }}
            width={400}
          />
        </div>
        <div className="grid grid-rows-2 p-4 gap-2">
          <div className="space-y-1">
            <h3 className="font-semibold text-base md:text-sm lg:text-base xl:text-sm">
              Running Shoes
            </h3>
            <p className="font-normal text-sm md:text-xs lg:text-sm xl:text-xs text-gray-500 dark:text-gray-400">
              Lightweight and breathable
            </p>
          </div>
          <div className="flex items-center justify-between">
            <h4 className="font-semibold text-sm md:text-xs lg:text-sm xl:text-xs">
              $49.99
            </h4>
            <Button size="sm" onClick={() => handleAddCart("Running Shoes")}>
              Add to Cart
            </Button>
          </div>
        </div>
      </div>
      <div className="flex flex-col rounded-lg overflow-hidden">
        <div className="flex-shrink-0 relative aspect-w-4 aspect-h-3">
          <img
            alt="Product 4"
            className="object-cover w-full h-full"
            height={300}
            src="/placeholder.svg"
            style={{
              aspectRatio: "400/300",
              objectFit: "cover",
            }}
            width={400}
          />
        </div>
        <div className="grid grid-rows-2 p-4 gap-2">
          <div className="space-y-1">
            <h3 className="font-semibold text-base md:text-sm lg:text-base xl:text-sm">
              Leather Wallet
            </h3>
            <p className="font-normal text-sm md:text-xs lg:text-sm xl:text-xs text-gray-500 dark:text-gray-400">
              Stylish and functional
            </p>
          </div>
          <div className="flex items-center justify-between">
            <h4 className="font-semibold text-sm md:text-xs lg:text-sm xl:text-xs">
              $29.99
            </h4>
            <Button size="sm" onClick={() => handleAddCart("Leather Wallet")}>
              Add to Cart
            </Button>
          </div>
        </div>
      </div>
    </section>
  );
}
